# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{antisamy}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sal Scotto"]
  s.date = %q{2011-03-14}
  s.description = %q{
    AntiSamy is a library to clean user-supplied HTML/CSS. This gem is a port of the anti-samy framework created for OWASP (http://www.owasp.org/index.php/Category:OWASP_AntiSamy_Project)
    AntiSamy works by using a policy to removed any dangerous input you specify from attributes to tags. This gem is built using nokogiri
  }
  s.email = %q{sal.scotto@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/antisamy.rb",
    "lib/antisamy/css/css_filter.rb",
    "lib/antisamy/css/css_scanner.rb",
    "lib/antisamy/css/css_validator.rb",
    "lib/antisamy/csspool/rsac.rb",
    "lib/antisamy/csspool/rsac/sac.rb",
    "lib/antisamy/csspool/rsac/sac/conditions.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/attribute_condition.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/begin_hyphen_condition.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/class_condition.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/combinator_condition.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/condition.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/id_condition.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/one_of_condition.rb",
    "lib/antisamy/csspool/rsac/sac/conditions/pseudo_class_condition.rb",
    "lib/antisamy/csspool/rsac/sac/document_handler.rb",
    "lib/antisamy/csspool/rsac/sac/error_handler.rb",
    "lib/antisamy/csspool/rsac/sac/generated_parser.rb",
    "lib/antisamy/csspool/rsac/sac/generated_property_parser.rb",
    "lib/antisamy/csspool/rsac/sac/lexeme.rb",
    "lib/antisamy/csspool/rsac/sac/lexical_unit.rb",
    "lib/antisamy/csspool/rsac/sac/parse_exception.rb",
    "lib/antisamy/csspool/rsac/sac/parser.rb",
    "lib/antisamy/csspool/rsac/sac/property_parser.rb",
    "lib/antisamy/csspool/rsac/sac/selectors.rb",
    "lib/antisamy/csspool/rsac/sac/selectors/child_selector.rb",
    "lib/antisamy/csspool/rsac/sac/selectors/conditional_selector.rb",
    "lib/antisamy/csspool/rsac/sac/selectors/descendant_selector.rb",
    "lib/antisamy/csspool/rsac/sac/selectors/element_selector.rb",
    "lib/antisamy/csspool/rsac/sac/selectors/selector.rb",
    "lib/antisamy/csspool/rsac/sac/selectors/sibling_selector.rb",
    "lib/antisamy/csspool/rsac/sac/selectors/simple_selector.rb",
    "lib/antisamy/csspool/rsac/sac/token.rb",
    "lib/antisamy/csspool/rsac/sac/tokenizer.rb",
    "lib/antisamy/csspool/rsac/stylesheet.rb",
    "lib/antisamy/csspool/rsac/stylesheet/rule.rb",
    "lib/antisamy/csspool/rsac/stylesheet/stylesheet.rb",
    "lib/antisamy/html/handler.rb",
    "lib/antisamy/html/sax_filter.rb",
    "lib/antisamy/html/scanner.rb",
    "lib/antisamy/model/attribute.rb",
    "lib/antisamy/model/css_property.rb",
    "lib/antisamy/model/tag.rb",
    "lib/antisamy/policy.rb",
    "lib/antisamy/scan_results.rb"
  ]
  s.homepage = %q{http://github.com/washu/antisamy-ruby}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{AntiSamy implmentation for Ruby.}
  s.test_files = [
    "spec/antisamy_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

